issueTrackerURL="https://www.github.com/xfacthd/framedblocks"
license="LGPL v3"

[[mods]]
    modId="framedblocks"
    version="${mod_version}"
    displayName="FramedBlocks"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/framedblocks"
    logoFile="logo.png"
    logoBlur=false
    authors="XFactHD"
    description='''Fancy building blocks'''



[[mixins]]
    config="framedblocks.mixin.json"



[[dependencies.framedblocks]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="atlasviewer"
    type="optional"
    versionRange="[${atlasviewer_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="buildinggadgets"
    type="optional"
    versionRange="[${buildinggadgets_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="create"
    type="optional"
    versionRange="[${create_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="diagonalblocks"
    type="optional"
    versionRange="[${diag_blocks_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="emi"
    type="optional"
    versionRange="[${emi_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="jei"
    type="optional"
    versionRange="[${jei_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="amendments"
    type="optional"
    versionRange="[${amendments_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="ae2"
    type="optional"
    versionRange="[${ae2_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="jade"
    type="optional"
    versionRange="[${jade_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="searchables"
    type="optional"
    versionRange="[${searchables_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="additionalplacements"
    type="optional"
    versionRange="[${additionalplacements_version},)"
    ordering="NONE"
    side="BOTH"
